  [AzureOpenai]
    api_key = "your_api_key_here"
    end_point = "your_end_point"
    api_version = "2023-07-01-preview"
    deployment_id = "your_deployment_id"
    model = "gpt-3.5-turbo-0613"
    temperature = 0.3
    top_p = 1
    max_tokens = 1000
    stop = "your_stop_here"
    presence_penalty = 0
    frequency_penalty = 0

    [AzureOpenai.MemoryAndClean]
      short_memory_token_limit=500
      clean_all=true
      clean_one=false

    [AzureOpenai.AzureEmbedding]
      deployment_id = "your_deployment_id"
      api_version = "2023-05-15"

  [AzureTTS]
    api_key = "your_api_key_here"
    end_point = "your_end_point"

    [AzureTTS.Speak]
      version = "1.0"
      xml_lang = "cn"
      xmlns_mstts = "https://www.w3.org/2001/mstts"
      xmlns = "http://www.w3.org/2001/10/synthesis"

    [AzureTTS.Voice]
      name = "zh-CN-XiaoyiNeural"
      effect = ""
      rate = "+25%"
      volume = "+0.00%"

  [AzureSTT]
    api_key = "your_api_key_here"
    speech_region = "your_speech_region_here"
    language = "your_language_here"
    format = "your_format_here"
