[XunFeiTTS]
api_key = "your_api_key_here"
api_secret = "your_api_secret_here"
app_id = "your_app_id_here"

[XunFeiTTS.XunFeiVoice]
aue = "your_aue_here"
sfl = 1
auf = "your_auf_here"
vcn = "your_vcn_here"
speed = 50
volume = 50
pitch = 50
reg = "your_reg_here"
rdn = "your_rdn_here"
