[XunFeiSpark]
HostURL = "wss://spark-api.xf-yun.com/v2.1/chat"
AppID = "YourAppID"
ApiKey = "YourAPIKey"
ApiSecret = "YourAPISecret"
Domain = "generalv2"
Temperature = 0.7
MaxTokens = 2048
TopK = 4
Auditing = "default"
Prompt = ''

[XunFeiSpark.MemoryAndClean]
ShortMemoryTokenLimit=500
CleanAll=true
CleanOne=false

[XunFeiTTS]
ApiKey = "your_api_key_here"
ApiSecret = "your_api_secret_here"
AppID = "your_app_id_here"

[XunFeiTTS.XunFeiVoice]
Aue = "your_aue_here"
Sfl = 1
Auf = "your_auf_here"
Vcn = "your_vcn_here"
Speed = 50
Volume = 50
Pitch = 50
Reg = "your_reg_here"
Rdn = "your_rdn_here"
